### PR TITLE
feat: deployment tuning

### PR DESCRIPTION
**Pull request by pietro-tota**
#### List of Changes
1. Decrease probes `initialDelaySeconds` since POD starts earlier since CPU limit increase
2. change rollout strategy to maxSurge 2 and maxUnavailable 0

#### Motivation and Context
1. Since CPU limit increase POD starts up faster so initial delay seconds can be lowered according to new startup time
2. previously rollout strategy was a complete pod substitution to reduce the amount of time needed for rolling out new pods: this stategy have a drow back in case of new release misconfiguration where pod cannot be started successfully and will cause all pods to be down.
This will not be always a problem during normal deployments with staging/prod strategy: during new pod deployments staging ones (clone of the prod configuration before deployment) are up and running.
In case of rolling update triggered by configuration update this strategy could lead to all pods being unavailable so a progressive rolling update strategy fits better here.
For the staging-prod deployment strategy this will make deployment phase last a bit longer but this will not be a problem thanks to the fact that staging deployment is the one that process events during production deployment

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by CianoDanilo — APPROVED** [review]

**Comment by CianoDanilo** [comment]
We could consider using a percentage while defining maxSurge (maybe 50%) to not change it later manually in case min replicas number changes.
Regarding point 2, why are you concerned about unavailability of application? In a rolling update scenario, with maxUnavailability set to 0, if we change a configmap k8s controller should start new pods without terminating current ones, right?

**Comment by CianoDanilo** [comment]
We could also consider maxSurge set to 100% and maxUnavailable set to 0 in order to resolve current strategy drawbacks while keeping the deployment phase speed as it is

**Comment by pietro-tota** [comment]
> We could consider using a percentage while defining maxSurge (maybe 50%) to not change it later manually in case min replicas number changes. Regarding point 2, why are you concerned about unavailability of application? In a rolling update scenario, with maxUnavailability set to 0, if we change a configmap k8s controller should start new pods without terminating current ones, right?

Yes, we could switch to percentage. I let absolute values here to have the same configuration as per other eCommerce modules.

About rolling update scenario: my worry is fixed by this PR. As for now rolling update perform deployment for all the pods at one time without leaving any pod up and running: here, in case of misconfiguration that prevents the pod to run properly all pods will be down until rollback. With progressive rolling update and maxUnavailabilty set to 0 this will not be the case anymore. I'm worry about the actual behavior that is fixed by this pr

**Comment by pietro-tota** [comment]
> We could also consider maxSurge set to 100% and maxUnavailable set to 0 in order to resolve current strategy drawbacks while keeping the deployment phase speed as it is

Yes we could do this but I prefer to have a progressive rolling update for the following reasons:
1. during normal deployment phase staging deployment pods are spin up (prod release duplication) -> this step require x2 prod resources allocation (duplicated pods). if we put maxSurge to 100% there will be a total resource request of x3 until pods rollout have been completed.
This lead to an excessive resource waste and could prevent other pods to spin up for autoscaling mechanism.
2. Normal deployment will have staging deployment up and running during new release rollout so a progressive rollout is acceptable and will cause no downtime since during deployments events are processed by the staging deployment, avoiding spin up too much pods: here we can spin up pod a bit at a time with no impact during on production traffic.

For rollout triggered outside a deployment pipeline pods will be substituted 2 at a time with a startup time of 30 seconds, making the whole process last 1:30 minute that is acceptable for a rollout.

This 2 pods to be spinned up at a time value can be changed in future in case of a minimum deployment replicas increase

**Review by ciuffagianluca — APPROVED** [review]

**Pull request merged**
