### PR TITLE
[CHK-1454] Add pgs API key for autogen clients

### PR DESCRIPTION
**Pull request by MarcoAGreco**
#### List of Changes

- Add pgs API key as helm values secret
- Add pgs API key in app resources
#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by infantesimone — APPROVED** [review]

**Review by giovanniberti — APPROVED** [review]
Remember to update README.md :)

**Review by Fernando-Granato — DISMISSED** [review]
Nice!😀

**Comment by MarcoAGreco** [comment]
> Remember to update README.md :)

Thanks 👍  done with [3d40247](https://github.com/pagopa/pagopa-ecommerce-event-dispatcher-service/pull/68/commits/3d4024702bbbc57d403c58e29d0da0d18b2a01e0) :)

**Review by infantesimone — DISMISSED** [review]

**Review by ciuffagianluca — APPROVED** [review]
LGTM!

**Pull request merged**
